include(cmake/FindSSE.cmake)
FindSSE()

if (SSE2_FOUND)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -msse2")
    message("using sse2")
endif()
if (SSE3_TRUE)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -msse3")
    message("using sse3")
endif()
if (SSE41_TRUE)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -msse4.1")
    message("using sse4_1")
endif()
if (SSE42_TRUE)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -msse4.2")
    message("using sse4_2")
endif()
if (AVX_TRUE)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mavx")
    message("using avx")
endif()
if (AVX2_TRUE)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mavx2")
    message("using avx2")
endif()
if (FMA_TRUE)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mfma")
    message("using FMA")
endif()
